### ISSUE TITLE
책 제목이 유사한 경우 제대로 정보를 갖고 오지 못하는 경우가 발생함.

### ISSUE THREAD

**Issue by shoo7830** [kmsk99/kr-book-info-plugin#10]
안녕하세요 
유용하게 만들어주신 옵시디언 플러그인을 잘 사용하고 있습니다. 

제가 정보를 갖고 오고 싶은 책은
[자바스크립트 자료구조와 알고리즘](https://www.yes24.com/Product/Goods/14419692) 이라는 책입니다.
제목을 `자바스크립트 자료구조와 알고리즘` 이라고 해서 새 노트를 만들고 해당 플러그인을 실행시키면
[자바스크립트로 하는 자료 구조와 알고리즘](https://www.yes24.com/Product/Goods/78165743)  이라는 책의 
정보를 불러옵니다. 

뭔가 설정에서도 바꿀수 있는 부분이 있을까 확인을 해봤으나 잘 모르겠어서 이슈로 남깁니다.

고맙습니다.

**Comment by shoo7830** [comment]
제가 정보를 갖고 오고 싶은 책의 상태가 '절판'이라서 
현재 절판이 아닌 정보중 가장 유사한 책의 정보를 갖고 오는 것으로 확인하였습니다.

**Comment by kmsk99** [comment]
동일한 책이름을 가지고 있다면 부제목 혹은 글쓴이를 같이 적는 것으로도 오류를 줄일수는 있습니다.
