### ISSUE TITLE
프론트매터를 제어할 수 있는 설정이 추가되면 좋겠습니다.

### ISSUE THREAD

**Issue by honggaruy** [kmsk99/kr-book-info-plugin#2]
제가 자주보는 "작가의 방"이라는 유튭채널에 이 플러그인이 소개되어 와봤습니다.

유튜브에서도 [자막으로 언급되었지만](https://youtu.be/qgJrf7l8CqU?t=178) 설정이 좀 추가되었으면 합니다

예를 들어 현재 고정된 형식으로 나오는 프론트매터가 설정할수 있는 형태로 제공된다면 좋을것 같습니다

**Comment by kmsk99** [comment]
일부 프론트매터 설정을 추가하였습니다
