### ISSUE TITLE
실행 불가

### ISSUE THREAD

**Issue by userrj0** [kmsk99/kr-book-info-plugin#9]
안녕하세요~ 옵시디언 문서 제목에 책 제목을 입력하고 실행시켰는데 메타정보 불러들이기가 안 됩니다. 사용법이 잘못된 건지... 궁금합니다.

**Comment by kmsk99** [comment]
현재 오류 재현이 불가능해서

어떤 책 제목을 쓰셨는지 알려주시거나 콘솔창에 뜬 오류를 알려주시면 해결 가능할 것 같습니다~

**Comment by userrj0** [comment]
다시 해 보니 잘됩니다. 설치 후 당일 안 돼서 문의했는데 이제는 문제없는 듯합니다. 덕분에 책 정보를 아주 쉽게 정리할 수 있습니다. 고맙습니다~
